[package]
name = "rust_random_lib"
version = "0.1.0"
edition = "2021"

[lib]
name = "rust_random_lib"
path = "src/lib.rs"

[dependencies]

[[example]]
name = "basic_usage"
path = "examples/basic_usage.rs"
